### ISSUE TITLE
Feedback trombone TODO

### ISSUE THREAD

**Issue by mulshine** [spiricom/stm32f7#2]
- [ ] Research speaker-mouthpiece coupling (Brass funnel, 3d print, etc)
- [ ] Research mouthpiece tech (IR, light, capacitive)
- [ ] DSP, improve compression algorithm
